<?php

/**
 * @file
 * Contains loan.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function loan_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the loan module.
    case 'help.page.loan':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for loan amortization schedule') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function loan_theme() {
  return [
    'loan' => [
      'render element' => 'children',
    ],
  ];
}
